/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.aulapoo.gescola.ui;

import javax.swing.JOptionPane;

/**
 *
 * @author psychoid
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        cursoMenuItem = new javax.swing.JMenuItem();
        disciplinaMenuItem = new javax.swing.JMenuItem();
        turmaMenuItem = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        responsavelMenuItem = new javax.swing.JMenuItem();
        alunoMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        colaboradorMenuItem = new javax.swing.JMenuItem();
        professorMenuItem = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        sairMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        novamatriculaMenuItem = new javax.swing.JMenuItem();
        consultarmatriculaMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Cadastros");

        cursoMenuItem.setMnemonic('x');
        cursoMenuItem.setText("Cursos");
        cursoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cursoMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(cursoMenuItem);

        disciplinaMenuItem.setText("Disciplinas");
        disciplinaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disciplinaMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(disciplinaMenuItem);

        turmaMenuItem.setMnemonic('T');
        turmaMenuItem.setText("Turmas");
        turmaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turmaMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(turmaMenuItem);
        fileMenu.add(jSeparator2);

        responsavelMenuItem.setMnemonic('o');
        responsavelMenuItem.setText("Responsáveis");
        responsavelMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                responsavelMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(responsavelMenuItem);

        alunoMenuItem.setMnemonic('s');
        alunoMenuItem.setText("Aluno (a)");
        alunoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alunoMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(alunoMenuItem);
        fileMenu.add(jSeparator1);

        colaboradorMenuItem.setText("Colaboradores");
        colaboradorMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colaboradorMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(colaboradorMenuItem);

        professorMenuItem.setText("Professores");
        professorMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                professorMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(professorMenuItem);
        fileMenu.add(jSeparator3);

        sairMenuItem.setText("Sair");
        sairMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(sairMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Matrícula");

        novamatriculaMenuItem.setMnemonic('t');
        novamatriculaMenuItem.setText("Nova Matrícula");
        novamatriculaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novamatriculaMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(novamatriculaMenuItem);

        consultarmatriculaMenuItem.setMnemonic('y');
        consultarmatriculaMenuItem.setText("Consultar");
        consultarmatriculaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarmatriculaMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(consultarmatriculaMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Ajuda");

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("Sobre");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 896, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sairMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairMenuItemActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_sairMenuItemActionPerformed

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        // TODO add your handling code here:
        frmSobre sobre = new frmSobre();
        sobre.show();
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void cursoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cursoMenuItemActionPerformed
        // TODO add your handling code here:
        ExibeMsgPadrao();
    }//GEN-LAST:event_cursoMenuItemActionPerformed

    private void disciplinaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disciplinaMenuItemActionPerformed
        // TODO add your handling code here:
        ExibeMsgPadrao();        
    }//GEN-LAST:event_disciplinaMenuItemActionPerformed

    private void turmaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turmaMenuItemActionPerformed
        // TODO add your handling code here:
         ExibeMsgPadrao();        
    }//GEN-LAST:event_turmaMenuItemActionPerformed

    private void responsavelMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_responsavelMenuItemActionPerformed
        // TODO add your handling code here:
         ExibeMsgPadrao();        
    }//GEN-LAST:event_responsavelMenuItemActionPerformed

    private void alunoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alunoMenuItemActionPerformed
        // TODO add your handling code here:
         ExibeMsgPadrao();        
    }//GEN-LAST:event_alunoMenuItemActionPerformed

    private void colaboradorMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colaboradorMenuItemActionPerformed
        // TODO add your handling code here:
         ExibeMsgPadrao();        
    }//GEN-LAST:event_colaboradorMenuItemActionPerformed

    private void professorMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_professorMenuItemActionPerformed
        // TODO add your handling code here:
         ExibeMsgPadrao();        
    }//GEN-LAST:event_professorMenuItemActionPerformed

    private void novamatriculaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novamatriculaMenuItemActionPerformed
        // TODO add your handling code here:
         ExibeMsgPadrao();        
    }//GEN-LAST:event_novamatriculaMenuItemActionPerformed

    private void consultarmatriculaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarmatriculaMenuItemActionPerformed
        // TODO add your handling code here:
         ExibeMsgPadrao();        
    }//GEN-LAST:event_consultarmatriculaMenuItemActionPerformed

    private void ExibeMsgPadrao(){
        JOptionPane.showMessageDialog(null, "Pesquise e aprenda a criar janelas GUI em java com o Netbeans, da uma olhada no menu [Sobre].. :)");
    }
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem alunoMenuItem;
    private javax.swing.JMenuItem colaboradorMenuItem;
    private javax.swing.JMenuItem consultarmatriculaMenuItem;
    private javax.swing.JMenuItem cursoMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem disciplinaMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem novamatriculaMenuItem;
    private javax.swing.JMenuItem professorMenuItem;
    private javax.swing.JMenuItem responsavelMenuItem;
    private javax.swing.JMenuItem sairMenuItem;
    private javax.swing.JMenuItem turmaMenuItem;
    // End of variables declaration//GEN-END:variables

}
